name: portfolioweb
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  modular_test:
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
